### ISSUE TITLE
Standardized configuration format

### ISSUE THREAD

**Issue by hSaria** [hSaria/ChromaTerm#58]
The current method for storing highlight rules has an arbitrary format that's a remanent of the original ChromaTerm. There's already a bug if someone attempts to use `{` or `}` as part of word match in their RegEx, but no one to my knowledge has run into it.

It would be better to use a well-known library/format to parse the configuration. I'm thinking of YAML, but that's not set in stone.

**Comment by cpriest** [comment]
YAML would work well, but you might consider [JSON5](https://json5.org/) instead.  It's JSON with the dumb stuff removed.

**Comment by hSaria** [comment]
I've taken a glance on JSON5. Looks interesting. Definitely up there with what I'm trying to decide on. Thanks for the suggestion.

**Comment by hSaria** [comment]
JSON5 doesn't seem to have well-established C libraries so that's gonna be risky to implement.

[libconfig](https://github.com/hyperrealm/libconfig) isn't too friendly if you're planning on modifying the file.

[TOML](https://github.com/toml-lang/toml) looks nice, but the two leading C parsers ([libtoml](https://github.com/ajwans/libtoml) and [tomlc99](https://github.com/cktan/tomlc99)) haven't been updated to v0.5.0 of the TOML spec which was released a year ago; I'd like to avoid abandoned projects.

**Comment by hSaria** [comment]
I'm thinking of the following format (currently in YAML for illustrative purposes only):
```yaml
highlights:
- description: Simple action that applies on the match
  regex: hello world
  color: green
  priority: 1000
- description: Group-specific actions
  regex: hello (world)
  color:
    0: green
    1: red
  priority: 1000
```

> The group-specific actions will be covered in #64. I just wanted to show how the above sample configuration would be able to accommodate for that.

**Comment by cpriest** [comment]
Hmm, this could support replacements as well, such as:
```yaml
highlights:
  description: Group-specific actions
  regex: hey (there)
  color:
    0: blue
    1: red
  replace:
    1: $1!!
```
Seems this could get pretty verbose though.

One advantage it would have though is nested matching such as:
```yaml
highlights:
- description: Simple action that applies on the match
  regex: (?i)hello world
  color: green
  priority: 1000
  highlights:
  - regex: WORLD
    color: yellow
```

The 2nd match of `WORLD` would only be checked if the parent regex matched.

Still, YAML is overly verbose to me.
