### ISSUE TITLE
Overlapping colors

### ISSUE THREAD

**Issue by Ren60FHk** [hSaria/ChromaTerm#69]
Hello!
I want to colorize the output of **show interfaces description** command in Cisco IOS in such a manner:
1. Colorize **admin down   down** (three words) to yellow. I want to do it only for interfaces which are down by admin.
2. Colorize **down   down** (two words) to red. I want to do it only for interfaces which are not down by admin.
I did some image editing for your better understanding what I want: https://imgur.com/6PIjLkY

I have the following config:
```
rules:
- description: down
  regex: down
  color: f#ff0000

- description: admin down
  regex: (?i)(admin down\s+down)
  color: f#f7e08b
```

Please see what I'm getting with my config: https://imgur.com/EE3KNUk
I understand that there is overlapping since presence of the word _down_ in both cases. In the versions prior to 0.4 I've successfully done it via priorities. So, how can I get what I want in the version 0.4 ?
Thanks!

**Comment by hSaria** [comment]
You can do it natively using RegEx with negative lookbehinds or using group-specific rules.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/34197532/64323250-0834f380-cfbc-11e9-9153-2b70a840962b.png">


Negative lookbehind (my recommendation unless you need variable-length lookbehind). 
```yaml
rules:
- description: down
  regex: (?i)(?<!admin\s)down\s+down
  color: f#ff0000

- description: admin down
  regex: (?i)admin down\s+down
  color: f#f7e08b
```


Group-specific rules. Since there's a variable-length pattern `\s{2,}`, it cannot be used as part of the lookbehind (most regex engines don't support it due to the performance implications), so group-specific rules would help here.  
```yaml
rules:
- description: down
  regex: (?i)\s{2,}(down\s+down)
  color: f#ff0000
  group: 1

- description: admin down
  regex: (?i)admin down\s+down
  color: f#f7e08b
```
