### ISSUE TITLE
Colorize multiple groups

### ISSUE THREAD

**Issue by Ren60FHk** [hSaria/ChromaTerm#70]
Is it possible to colorize multiple groups ?

**Comment by hSaria** [comment]
I'll get this fixed today in v0.4.1. It'll be something like this.

```yaml
rules:
- description: hello world
  regex: Hello (World)! It's (me)
  color: 
    1: f#abcabc
    2: b#123123
```

> The `group` key in a rule will be deprecated, but still supported for a while.
