### ISSUE TITLE
Bold text style matches everything?

### ISSUE THREAD

**Issue by heigren** [hSaria/ChromaTerm#73]
## Description
When using the "bold" it matches everything after the initial match, while the color configured on the same rule is displaying correctly. The bold style continues until the session is closed. `ct --reload` does not help either.

![Screenshot from 2019-10-09 11-33-33](https://user-images.githubusercontent.com/726720/66469765-bdaa0980-ea88-11e9-880d-57033d321f42.png)

## Environment
-   OS: Ubuntu 19.04
-   ChromaTerm: 0.4.8

## Configuration
```yaml
  regex: (?:[0-9]*[1-9][0-9]*\W|^)((input errors|errors|error|err|reset|act\/unsup|dhcp|DHCP|mismatch|notconnect|drops|dropped|runts|CRC|collisions|collision|LRN|learning
|listening|LIS|unsynchronized))(?=[\W\s]|$)
  color: f#c94b4b bold
```
